# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kirill Liubimov
title: Senior Mobile Developer
email: dev.lyubimov.kirill@gmail.com
website: www.lkirill.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: kirillrg
github_username: rotorgames
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: kirill-lyubimov-06a68712b
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Kirill, a Senior Mobile Developer with <b>10+ years</b> of software development experience. I specialize in <b>cross-platform</b> mobile development for <b>Android</b> and <b>iOS</b>, with over <b>7 years</b> of dedicated expertise in this field.

  My passion for crafting <b>high-performance</b> and <b>user-friendly</b> applications has driven me to stay at the forefront of mobile technology advancements. 
  Throughout my career, I've successfully delivered <b>cutting-edge</b> solutions that blend seamless functionality with <b>striking design</b>.

  With a deep understanding of both <b>native</b> and <b>hybrid</b> frameworks, I pride myself on creating versatile apps that reach a broader audience without compromising on performance or user experience. 
  My strong <b>problem-solving</b> skills and <b>attention to detail</b> allow me to tackle complex challenges and <b>optimize application efficiency</b>.

  As a proactive <b>team player</b>, I thrive in collaborative environments, fostering open communication to ensure projects meet and exceed expectations. 
  I take great pleasure in <b>mentoring</b> junior developers, <b>sharing my knowledge</b>, and <b>continuously learning</b> from others to stay adaptable in an ever-evolving tech landscape.

  I'm eager to contribute my expertise to innovative projects that push the boundaries of mobile development and make a meaningful impact on users' lives. 
  Let's connect and explore how we can create the next generation of exceptional mobile experiences together.

  My skils: <mark>Dart</mark> <mark>Flutter</mark> <mark>FFI</mark> <mark>C#</mark> <mark>Xamarin.Forms</mark> <mark>Xamarin</mark> <mark>CI/CD</mark> <mark>Design Patterns</mark> <mark>Programming Techniques</mark>

content:
  - title: Articles
    layout: list
    content:
      - layout: top-middle
        title: Flutter — pigeon with build_runner
        link: https://medium.com/@lkirill/686a7ccfb2ca
        description:
          Presenting my article on the remarkable self-developed package [<mark>pigeon_build_runner</mark>](https://pub.dev/packages/pigeon_build_runner){:target="_blank"} for Flutter. 
          

          This insightful piece aims to introduce the package, elucidate the problems it effectively solves, and provide a comprehensive guide on how to seamlessly integrate it into your Flutter projects. 
          

          Moreover, I shed light on some fascinating features of the build_runner that are sure to capture your interest. 
          
          
          So, let's dive in and explore the world of pigeon_build_runner and its contributions to the Flutter ecosystem.
  - title: Open Source Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: pigeon_build_runner
        link: pub.dev/packages/pigeon_build_runner
        quote: >
          Here's I embarked on a profound journey into the realm of Dart code generation processes and the art of working with native code.
        description: | # this will include new lines to allow paragraphs
          The [<mark>pigeon_build_runner</mark>](https://pub.dev/packages/pigeon_build_runner){:target="_blank"} is a powerful Dart package that seamlessly integrates the pigeon package with the build_runner package, enhancing the efficiency and simplicity of code generation for Flutter projects. The package acts as a bridge between pigeon and build_runner, streamlining the communication process and automating the code generation workflow.
      - layout: left
        title: Rg.Plugins.Popup
        link: github.com/rotorgames/Rg.Plugins.Popup
        quote: >
          This is probably one of the most popular Xamarin.Forms library so far.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way to bring popups in Xamarin.Forms. 

          I even couldn't imagine that the project would become so popular and achive more then [![NuGet Downloads](https://img.shields.io/nuget/dt/rg.plugins.popup?color=black&label=%20)](https://www.nuget.org/packages/Rg.Plugins.Popup/){:target="_blank"} downloads and [![GitHub Stars](https://img.shields.io/github/stars/rotorgames/rg.plugins.popup?color=black&label=%20)](https://github.com/rotorgames/Rg.Plugins.Popup){:target="_blank"} stars on GitHub.
          
          If you don't have a project as awesome as this I would advise you to make one.
      - layout: left
        title: Rg.DiffUtils
        link: github.com/rotorgames/Rg.DiffUtils
        quote: >
          This is a result of my passionate diving through algorithms.
        description: | # this will include new lines to allow paragraphs
          The library is an implementation of Eugene W. Myers's algorithm which allows finding differences and movements in collections.

          My goal was to bring a simple and powerful way at the same time to merge collections without useless redraws of UI in .NET

          I was inspired by AndroidX.DiffUtil when creating the library.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shping
        link: shping.com
        # link_text: boringcompany.com
        sub_title: Senior Mobile Developer
        caption: April 2017 - Present
        quote: >
          Designing and developing Xamarin.Forms application, configuring CI/CD, creating packages and etc.
        description: | # this will include new lines to allow paragraphs
          Working at Shping I had the pleasure of getting to know technologies such as barcode scanning, drawing via SkiaSharp, machine learning with Google ML Kit, Blockchain, etc.

          Also, I bint a lot of libraries from java/objective-c to CSharp for internal usage, and developed an extension of Visual Studio For Mac which updates localizable resources.

          Shping is an amazing place where I can develop and discover new things.
      - layout: left
        title: Incredible Artstudio
        link: incredibleart.ru
        # link_text: boringcompany.com
        sub_title: Mobile Developer
        caption: February 2017 - April 2017
        quote: >
          Designing and developing Xamarin.Forms application as a Freelancer
        description: | # this will include new lines to allow paragraphs
          Developing the application with Xamarin.Forms for streaming live TV and archive. Integration with API Middleware, testing.
      - layout: left
        title: ITECHNET Ltd.
        link: freshwindhotel.ru
        # link_text: boringcompany.com
        sub_title: Mobile Developer
        caption: September 2016 - February 2017
        quote: >
          Designing, developing and publishing Xamarin.Forms application as a Freelancer
        description: | # this will include new lines to allow paragraphs
          Creating an application for the Hotel with Xamarin.Forms, testing, publishing and contributing to the application.
          Also, I took care of all work around the documentation for backend developers.

          [Google Play](https://play.google.com/store/apps/details?id=ru.rotorgames.freshwind)
          [App Store](https://itunes.apple.com/ru/app/id1185871011?mt=8)
      - layout: left
        title: Freelance Work
        # link_text: boringcompany.com
        sub_title: Mobile Developer
        caption: January 2014 - September 2016
        quote: >
          Designing, developing and publishing Xamarin.Forms application as a Freelancer
        description: | # this will include new lines to allow paragraphs
          During 2014-2016 I was working on several Xamarin.Forms and phonegap projects as Freelancer. 
          I got more experience around Xamarin.Forms, Google Maps, Couchbase Lite, Syncfusion, offline work and etc.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Astrakhan State Technical University
        caption: 2021 - Present
        sub_title: Informatics and computer technology
        quote: >
          Established in 1930, Astrakhan State Technical University is one of the oldest higher education institutions in the country.
        description: | # this will include new lines to allow paragraphs
          I decided to continue my education at the university after my graduation in 2019 to get a master's degree.

      - layout: left
        title: Astrakhan State Technical University
        caption: 2015 - 2019
        sub_title: Electronics and electrical engineering
        quote: >
          Established in 1930, Astrakhan State Technical University is one of the oldest higher education institutions in the country.
        description: | # this will include new lines to allow paragraphs
          During my time at the university I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. 
          
          I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I got a bachelor degree when I graduated from university.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in mobile development and software engineering some of my other interests and hobbies are:
      - Traveling 
      - Snowboarding
      - [Improving my work-life balance with machine learning of course](https://www.youtube.com/watch?v=Rgx8dpiPwpA){:target="_blank"}

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
